### ISSUE TITLE
!kick

### ISSUE THREAD

**Issue by almostSouji** [Comfy-Mittens/Embot#2]
`!kick <user> <reason (optional)>`

**user:**
raw ID, @mention
**reason;**
text

**functionality:**
* Permission check - kick user
* Message: Do you want to kick this user?
[rich embed like !find result]
* User input: Yes/y No/n
* Kicks user, audit log (User: Name (ID) - Reason (if provided)
* Message: Invoking User kicked User with reason:

**Comment by Comfy-Mittens** [comment]
Tested and ready, probably.
