### ISSUE TITLE
!ban

### ISSUE THREAD

**Issue by almostSouji** [Comfy-Mittens/Embot#3]
`!ban<user> <reason (optional)>`

**user:**
raw ID, @mention
**reason;**
text

**functionality:**
* Permission check - ban user
* Message: Do you want to ban this user?
[rich embed like !find result]
* User input: Yes/y No/n
* Bans user, audit log (User: Name (ID) - Reason (if provided)
* Message: Invoking User banned User with reason:

**Comment by Comfy-Mittens** [comment]
Format for adding bans
``IGuild.AddBanAsync(IUse user, int pruneDays, string reason)``

Need a parameter for prune days.

**Comment by Comfy-Mittens** [comment]
Two commands:

``ban User Days Reason`` and ``ban User Reason``
