### ISSUE TITLE
!jumbo

### ISSUE THREAD

**Issue by almostSouji** [Comfy-Mittens/Embot#4]
`!jumbo <emoji>`
Downloads emoji, uploads them as a file

[11:56 PM] Sajuuk: jumbo queries the url directly using aiohttp and retrieves a bytes object of whatever was queried
<https://github.com/Azareal/SajuukBot/blob/py-dev/python/commands.py#L189>

![untitled](https://user-images.githubusercontent.com/26532370/29474535-66106078-845c-11e7-987e-56eb553370ed.png)

**Comment by Comfy-Mittens** [comment]
I understand now~
